// AUTO-GENERATED by scripts bundling (do not edit by hand).
// Representative smichov wall + 43-hold subset for the Chalkbag native rendering playground.
import type { Float3 } from 'react-native-filament'

export type HoldDef = { id: string; glb: number; center: Float3; normal: Float3; color: string }
export type RouteDef = { id: string; name: string | null; circuit: string | null; grade: string | null; color: string; holdIds: string[] }
export type AreaDef = { index: number; name: string; glb: number; labelPos: Float3 }

export const skyStrongKtx = require('@assets/cb_sky_strong.ktx') as number
export const skyChalkKtx = require('@assets/cb_sky.ktx') as number
export const unlitTexturedMat = require('@assets/cb_unlit_textured.filamat') as number
export const unlitTexturedOverlayMat = require('@assets/cb_unlit_textured_overlay.filamat') as number
export const envIblKtx = require('@assets/cb_env_ibl.ktx') as number
export const maskWhiteMat = require('@assets/cb_mask_white.filamat') as number
export const maskBlackMat = require('@assets/cb_mask_black.filamat') as number
export const outlinePostMat = require('@assets/cb_outline_post.filamat') as number

export const holds: HoldDef[] = [
  { id: "object_1Py2Y4mX", glb: require('@assets/cb_object_1Py2Y4mX.glb'), center: [5.503906938236458, 0.4439143333333334, -9.916633881567218], normal: [0.34818372030104205, -0.2583800048699638, -0.9011147929097176], color: "blue" },
  { id: "object_hCyMPViQ", glb: require('@assets/cb_object_hCyMPViQ.glb'), center: [5.3970935029905664, 1.8185459855072466, -10.329488412292534], normal: [-0.6168367218837382, -0.20382081467927934, -0.760243075627262], color: "blue" },
  { id: "object_z85pxhmU", glb: require('@assets/cb_object_z85pxhmU.glb'), center: [5.740852038967331, 2.8518522976190477, -10.409835466157098], normal: [0.4958097913828719, 0.04717835394426794, -0.8671486917985765], color: "blue" },
  { id: "object_lSU7wmXF", glb: require('@assets/cb_object_lSU7wmXF.glb'), center: [6.015648226344919, 3.3919968156028366, -10.224008424465826], normal: [0.49420953287138647, 0.05047787534753605, -0.8678760981381183], color: "blue" },
  { id: "object_p81FlgDF", glb: require('@assets/cb_object_p81FlgDF.glb'), center: [6.069203247259853, 2.2074822314814817, -10.20388224440413], normal: [0.3481837203009134, -0.2583800048699577, -0.901114792909769], color: "blue" },
  { id: "object_LW0AW1RR", glb: require('@assets/cb_object_LW0AW1RR.glb'), center: [6.20672213328182, 3.1791815729166664, -10.125577407751607], normal: [0.49580979138342895, 0.04717835394448781, -0.867148691798246], color: "blue" },
  { id: "object_hX2e1VDS", glb: require('@assets/cb_object_hX2e1VDS.glb'), center: [5.717474678453025, 3.7305276756756753, -10.37230348727465], normal: [0.4942095328716968, 0.050477875347392835, -0.86787609813795], color: "blue" },
  { id: "object_VotzXDtf", glb: require('@assets/cb_object_VotzXDtf.glb'), center: [5.415615673905087, 1.478930583333333, -10.230756684333493], normal: [0.34818372030114203, -0.2583800048700348, -0.9011147929096587], color: "blue" },
  { id: "object_xTzQJ2oq", glb: require('@assets/cb_object_xTzQJ2oq.glb'), center: [-1.25968338010536, 2.4528403333333335, 11.215047052593276], normal: [-0.7040891848725785, -0.11174155282857848, -0.7012647468088825], color: "blue" },
  { id: "object_4LxTJ0jb", glb: require('@assets/cb_object_4LxTJ0jb.glb'), center: [-2.6145102631406565, 1.4652283333333334, 12.747962019050375], normal: [-0.7047985013483594, -0.10517905526556, -0.701567130665734], color: "blue" },
  { id: "object_oqUJUvt8", glb: require('@assets/cb_object_oqUJUvt8.glb'), center: [-1.7987772781507396, 2.5474223030303027, 11.744135006509088], normal: [-0.7081902919046552, -0.11650064955559564, -0.6963433844771727], color: "blue" },
  { id: "object_8WW1YIFB", glb: require('@assets/cb_object_8WW1YIFB.glb'), center: [-2.570362510931996, 0.6732373913043479, 12.810863593795174], normal: [-0.7047985013481096, -0.10517905526544702, -0.7015671306660017], color: "blue" },
  { id: "object_VFkmaHi2", glb: require('@assets/cb_object_VFkmaHi2.glb'), center: [-1.8924721846671013, 3.416549124378109, 11.692892548593965], normal: [-0.7040891848723694, -0.11174155282888315, -0.7012647468090439], color: "blue" },
  { id: "object_Y3XKY2uD", glb: require('@assets/cb_object_Y3XKY2uD.glb'), center: [-0.9842925201336139, 0.9230584552845529, 11.187006229553061], normal: [-0.7081902919037736, -0.1165006495561191, -0.6963433844779818], color: "blue" },
  { id: "object_2ISTEbTK", glb: require('@assets/cb_object_2ISTEbTK.glb'), center: [-2.3592310121552766, 2.84355284057971, 12.26059967725944], normal: [-0.7081902919041216, -0.116500649556044, -0.6963433844776404], color: "blue" },
  { id: "object_rdC3QgCz", glb: require('@assets/cb_object_rdC3QgCz.glb'), center: [-1.687724119609873, 1.8876593538011692, 11.726533520116012], normal: [-0.7081902919041158, -0.11650064955611568, -0.6963433844776343], color: "blue" },
  { id: "object_MOabpOTx", glb: require('@assets/cb_object_MOabpOTx.glb'), center: [-2.258001074437112, 1.544234019379845, 12.3613477331966], normal: [-0.7047985013479886, -0.10517905526548214, -0.7015671306661181], color: "blue" },
  { id: "object_KBjNAtUb", glb: require('@assets/cb_object_KBjNAtUb.glb'), center: [-1.0419381387669904, 0.1901722777777778, 11.359306085034111], normal: [-0.7047985013482646, -0.10517905526545766, -0.7015671306658444], color: "blue" },
  { id: "object_UEgo0HaE", glb: require('@assets/cb_object_UEgo0HaE.glb'), center: [-1.55989152438848, 3.977142463768115, 11.266957448350693], normal: [-0.7040891848723315, -0.11174155282874842, -0.7012647468091036], color: "blue" },
  { id: "object_WeFCZlqA", glb: require('@assets/cb_object_WeFCZlqA.glb'), center: [-2.381841521615406, 2.317398372222222, 12.373897114779245], normal: [-0.708190291904185, -0.11650064955609571, -0.6963433844775673], color: "blue" },
  { id: "object_OQNcth2a", glb: require('@assets/cb_object_OQNcth2a.glb'), center: [2.1723152787933646, 3.142389761904762, 1.7459090442885161], normal: [0.6578315706387781, -0.44801453664488905, 0.6054259654373801], color: "yellow" },
  { id: "object_MCA3W8jg", glb: require('@assets/cb_object_MCA3W8jg.glb'), center: [2.1726900456853553, 2.22424193814433, 1.0859193654445782], normal: [0.6578315706385233, -0.44801453664475915, 0.605425965437753], color: "yellow" },
  { id: "object_mBhMCHI4", glb: require('@assets/cb_object_mBhMCHI4.glb'), center: [1.5555591209842579, 2.5771975238095246, 2.0254425517132892], normal: [0.6578315706385119, -0.44801453664470087, 0.6054259654378086], color: "yellow" },
  { id: "object_5UwnC5BB", glb: require('@assets/cb_object_5UwnC5BB.glb'), center: [1.0265280948135977, 1.451477327044025, 1.7457351938533474], normal: [0.6578315706385041, -0.44801453664478363, 0.6054259654377558], color: "yellow" },
  { id: "object_xzlE8Fvo", glb: require('@assets/cb_object_xzlE8Fvo.glb'), center: [0.8244831689291061, 2.3264866222222222, 2.6066419480014167], normal: [0.6578315706384054, -0.4480145366446158, 0.6054259654379873], color: "yellow" },
  { id: "object_DJpb1yHO", glb: require('@assets/cb_object_DJpb1yHO.glb'), center: [1.8821847917559396, 2.9781826854460083, 1.9666471403528938], normal: [0.6578315706385054, -0.4480145366446929, 0.6054259654378215], color: "yellow" },
  { id: "object_kYlLs35V", glb: require('@assets/cb_object_kYlLs35V.glb'), center: [0.47872015745667795, 0.8443536184738955, 1.8873239618194848], normal: [0.6578315706387629, -0.448014536644687, 0.6054259654375461], color: "yellow" },
  { id: "object_jojKnw9j", glb: require('@assets/cb_object_jojKnw9j.glb'), center: [0.9511810880125839, 0.8897177878787879, 1.4057697877674147], normal: [0.6578315706386693, -0.44801453664442137, 0.6054259654378444], color: "yellow" },
  { id: "object_PerMGc2e", glb: require('@assets/cb_object_PerMGc2e.glb'), center: [2.44272664606782, 3.457046565656565, 1.5478003839564711], normal: [0.6932553568401656, -0.026335450238934764, 0.7202107013042275], color: "yellow" },
  { id: "object_qER12zF3", glb: require('@assets/cb_object_qER12zF3.glb'), center: [2.726038466276141, 3.6624990392156853, 1.2733577807699956], normal: [0.6932553568401467, -0.02633545023892813, 0.720210701304246], color: "yellow" },
  { id: "object_vtN5Xdur", glb: require('@assets/cb_object_vtN5Xdur.glb'), center: [2.8044814678790475, 3.906830672727274, 1.2160335639667097], normal: [0.6932553568401281, -0.026335450238907245, 0.7202107013042647], color: "yellow" },
  { id: "object_BNkCYwQH", glb: require('@assets/cb_object_BNkCYwQH.glb'), center: [1.4339122452936515, 1.095399128205128, 1.0427861890241572], normal: [0.657831570638505, -0.44801453664458857, 0.6054259654378993], color: "yellow" },
  { id: "object_DoyROXgg", glb: require('@assets/cb_object_DoyROXgg.glb'), center: [0.7701299863095095, 1.7410201259259268, 2.2524298235421503], normal: [0.6578315706384559, -0.44801453664469426, 0.6054259654378742], color: "yellow" },
  { id: "object_4lmfBePo", glb: require('@assets/cb_object_4lmfBePo.glb'), center: [1.6582906677019853, 1.83836796969697, 1.3394531018786022], normal: [0.6578315706387045, -0.4480145366446358, 0.6054259654376475], color: "yellow" },
  { id: "object_z1Q4VH1F", glb: require('@assets/cb_object_z1Q4VH1F.glb'), center: [-21.369083021458195, 0.32033829710144923, -4.296257133502155], normal: [0.675006595606674, -0.06563119811807232, -0.7348868223890496], color: "yellow" },
  { id: "object_uIe95dMa", glb: require('@assets/cb_object_uIe95dMa.glb'), center: [-21.381231522488346, 1.7780018405797102, -4.443246966926923], normal: [0.6750065956067174, -0.0656311981180429, -0.7348868223890123], color: "yellow" },
  { id: "object_HFchykJI", glb: require('@assets/cb_object_HFchykJI.glb'), center: [-21.299669554511638, 3.6361917352941173, -4.532078715137907], normal: [0.6768230561545862, -0.06141648271836162, -0.7335792842686272], color: "yellow" },
  { id: "object_2diXqfhF", glb: require('@assets/cb_object_2diXqfhF.glb'), center: [-21.81983021293815, 1.371580205673759, -4.802825189585823], normal: [0.6750065956063985, -0.06563119811806722, -0.7348868223893029], color: "yellow" },
  { id: "object_DIsfghOj", glb: require('@assets/cb_object_DIsfghOj.glb'), center: [-21.322151016888043, 2.7524184434782613, -4.489752817865234], normal: [0.6699195494481741, -0.06808130443693043, -0.7393055750184233], color: "yellow" },
  { id: "object_BGZxjyVb", glb: require('@assets/cb_object_BGZxjyVb.glb'), center: [-21.285933531477983, 0.9249259423076924, -4.274136682618678], normal: [0.6750065956067525, -0.06563119811799137, -0.7348868223889846], color: "yellow" },
  { id: "object_EEAWrNDy", glb: require('@assets/cb_object_EEAWrNDy.glb'), center: [-21.072607844373913, 1.9082113333333333, -4.164116958902647], normal: [0.6699195494483142, -0.0680813044370612, -0.7393055750182841], color: "yellow" },
  { id: "object_jr2fUVrk", glb: require('@assets/cb_object_jr2fUVrk.glb'), center: [-20.863650510564508, 3.0150067839506165, -4.073522175647651], normal: [0.6768230561546694, -0.06141648271833193, -0.7335792842685527], color: "yellow" },
  { id: "object_qydF8DiM", glb: require('@assets/cb_object_qydF8DiM.glb'), center: [-21.748570158700183, 0.9823896194690265, -4.711557275329862], normal: [0.6750065956067598, -0.06563119811805208, -0.7348868223889725], color: "yellow" },
]

export const routes: RouteDef[] = [
  { id: "route_IYBOQcvG", name: null, circuit: "Modrá", grade: null, color: "blue", holdIds: ["object_1Py2Y4mX","object_hCyMPViQ","object_z85pxhmU","object_lSU7wmXF","object_p81FlgDF","object_LW0AW1RR","object_hX2e1VDS","object_VotzXDtf"] },
  { id: "route_uomeFalL", name: null, circuit: "Modrá", grade: null, color: "blue", holdIds: ["object_xTzQJ2oq","object_4LxTJ0jb","object_oqUJUvt8","object_8WW1YIFB","object_VFkmaHi2","object_Y3XKY2uD","object_2ISTEbTK","object_rdC3QgCz","object_MOabpOTx","object_KBjNAtUb","object_UEgo0HaE","object_WeFCZlqA"] },
  { id: "route_ji2XQNFy", name: null, circuit: "Žlutá", grade: null, color: "yellow", holdIds: ["object_OQNcth2a","object_MCA3W8jg","object_mBhMCHI4","object_5UwnC5BB","object_xzlE8Fvo","object_DJpb1yHO","object_kYlLs35V","object_jojKnw9j","object_PerMGc2e","object_qER12zF3","object_vtN5Xdur","object_BNkCYwQH","object_DoyROXgg","object_4lmfBePo"] },
  { id: "route_T1kbJgkS", name: null, circuit: "Žlutá", grade: null, color: "yellow", holdIds: ["object_z1Q4VH1F","object_uIe95dMa","object_HFchykJI","object_2diXqfhF","object_DIsfghOj","object_BGZxjyVb","object_EEAWrNDy","object_jr2fUVrk","object_qydF8DiM"] },
]

export const areas: AreaDef[] = [
  { index: 0, name: "Banán", glb: require('@assets/cb_area_0.glb'), labelPos: [-10.21768823340493, 3.448931403303847, 4.902812100634006] },
  { index: 2, name: "Loď 2", glb: require('@assets/cb_area_2.glb'), labelPos: [3.1348071666090047, 3.82898373917367, -2.666874371448525] },
]
