// AUTO-GENERATED by scripts bundling (do not edit by hand).
// Representative smichov wall + 43-hold subset for the Chalkbag native rendering playground.
import type { Float3 } from 'react-native-filament'

export type HoldDef = { id: string; glb: number; center: Float3; normal: Float3; color: string }
export type RouteDef = { id: string; name: string | null; circuit: string | null; holdIds: string[] }

export const wallGlb = require('@assets/cb_wall.glb') as number
export const skyStrongKtx = require('@assets/cb_sky_strong.ktx') as number
export const skyChalkKtx = require('@assets/cb_sky.ktx') as number

export const holds: HoldDef[] = [
  { id: "object_1Py2Y4mX", glb: require('@assets/cb_object_1Py2Y4mX.glb'), center: [9.399114870370374, 0.4439143333333334, 5.615333342592594], normal: [0.22325954553828423, -0.25838000486996376, 0.9398909236764851], color: "blue" },
  { id: "object_hCyMPViQ", glb: require('@assets/cb_object_hCyMPViQ.glb'), center: [9.720929391304349, 1.8185459855072466, 5.8951428985507235], normal: [0.9389016178220487, -0.2038208146792793, 0.27734604297630483], color: "blue" },
  { id: "object_z85pxhmU", glb: require('@assets/cb_object_z85pxhmU.glb'), center: [9.483085261904762, 2.8518522976190477, 6.156017869047618], normal: [0.08234717076841484, 0.047178353944267934, 0.9954863868408984], color: "blue" },
  { id: "object_lSU7wmXF", glb: require('@assets/cb_object_lSU7wmXF.glb'), center: [9.151364432624115, 3.3919968156028366, 6.158452092198583], normal: [0.08407805527027438, 0.05047787534753604, 0.9951798152707717], color: "blue" },
  { id: "object_p81FlgDF", glb: require('@assets/cb_object_p81FlgDF.glb'), center: [9.095825962962964, 2.2074822314814817, 6.1721882407407405], normal: [0.22325954553841945, -0.25838000486995766, 0.9398909236764547], color: "blue" },
  { id: "object_LW0AW1RR", glb: require('@assets/cb_object_LW0AW1RR.glb'), center: [8.938137999999999, 3.1791815729166664, 6.185514822916668], normal: [0.08234717076776873, 0.04717835394448779, 0.9954863868409415], color: "blue" },
  { id: "object_hX2e1VDS", glb: require('@assets/cb_object_hX2e1VDS.glb'), center: [9.481101747747749, 3.7305276756756753, 6.111845297297298], normal: [0.08407805526992335, 0.05047787534739283, 0.9951798152708088], color: "blue" },
  { id: "object_VotzXDtf", glb: require('@assets/cb_object_VotzXDtf.glb'), center: [9.64975686111111, 1.478930583333333, 5.824252166666667], normal: [0.2232595455381684, -0.25838000487003476, 0.9398909236764931], color: "blue" },
  { id: "object_xTzQJ2oq", glb: require('@assets/cb_object_xTzQJ2oq.glb'), center: [-14.305796470588238, 2.4528403333333335, 15.717483529411766], normal: [-0.2656473141756389, -0.11174155282857848, -0.9575726237955675], color: "blue" },
  { id: "object_4LxTJ0jb", glb: require('@assets/cb_object_4LxTJ0jb.glb'), center: [-16.241100694444444, 1.4652283333333334, 16.38079472222222], normal: [-0.2661145919081233, -0.10517905526555998, -0.958185989412816], color: "blue" },
  { id: "object_oqUJUvt8", glb: require('@assets/cb_object_oqUJUvt8.glb'), center: [-15.035909090909092, 2.5474223030303027, 15.911111666666665], normal: [-0.2716444743213368, -0.11650064955559566, -0.9553203013774014], color: "blue" },
  { id: "object_8WW1YIFB", glb: require('@assets/cb_object_8WW1YIFB.glb'), center: [-16.233797801932376, 0.6732373913043479, 16.457295048309174], normal: [-0.2661145919077739, -0.10517905526544705, -0.9581859894129255], color: "blue" },
  { id: "object_VFkmaHi2", glb: require('@assets/cb_object_VFkmaHi2.glb'), center: [-15.092049353233827, 3.416549124378109, 15.820266766169153], normal: [-0.26564731417537724, -0.11174155282888315, -0.9575726237956045], color: "blue" },
  { id: "object_Y3XKY2uD", glb: require('@assets/cb_object_Y3XKY2uD.glb'), center: [-14.052514878048777, 0.9230584552845529, 15.829174390243907], normal: [-0.27164447432017047, -0.1165006495561191, -0.9553203013776691], color: "blue" },
  { id: "object_2ISTEbTK", glb: require('@assets/cb_object_2ISTEbTK.glb'), center: [-15.778354975845408, 2.84355284057971, 16.083211207729466], normal: [-0.2716444743206418, -0.116500649556044, -0.9553203013775443], color: "blue" },
  { id: "object_rdC3QgCz", glb: require('@assets/cb_object_rdC3QgCz.glb'), center: [-14.930661871345027, 1.8876593538011692, 15.950679824561396], normal: [-0.27164447432063965, -0.11650064955611568, -0.9553203013775361], color: "blue" },
  { id: "object_MOabpOTx", glb: require('@assets/cb_object_MOabpOTx.glb'), center: [-15.740124263565894, 1.544234019379845, 16.22081965116279], normal: [-0.2661145919076113, -0.10517905526548217, -0.9581859894129668], color: "blue" },
  { id: "object_KBjNAtUb", glb: require('@assets/cb_object_KBjNAtUb.glb'), center: [-14.187765185185183, 0.1901722777777778, 15.950490555555556], normal: [-0.26611459190798636, -0.10517905526545766, -0.9581859894128653], color: "blue" },
  { id: "object_UEgo0HaE", glb: require('@assets/cb_object_UEgo0HaE.glb'), center: [-14.592448260869565, 3.977142463768115, 15.614282898550725], normal: [-0.26564731417531495, -0.11174155282874842, -0.9575726237956376], color: "blue" },
  { id: "object_WeFCZlqA", glb: require('@assets/cb_object_WeFCZlqA.glb'), center: [-15.853992611111105, 2.317398372222222, 16.170540999999997], normal: [-0.271644474320733, -0.11650064955609571, -0.955320301377512], color: "blue" },
  { id: "object_OQNcth2a", glb: require('@assets/cb_object_OQNcth2a.glb'), center: [5.541356404761905, 3.142389761904762, -5.8838888095238095], normal: [-0.885027684881019, -0.44801453664488894, -0.12652656617884325], color: "yellow" },
  { id: "object_MCA3W8jg", glb: require('@assets/cb_object_MCA3W8jg.glb'), center: [5.914759714776633, 2.22424193814433, -5.339686195876289], normal: [-0.8850276848810202, -0.44801453664475915, -0.12652656617929486], color: "yellow" },
  { id: "object_mBhMCHI4", glb: require('@assets/cb_object_mBhMCHI4.glb'), center: [5.891429073593074, 2.5771975238095246, -6.463523406926407], normal: [-0.8850276848810422, -0.4480145366447008, -0.12652656617934716], color: "yellow" },
  { id: "object_5UwnC5BB", glb: require('@assets/cb_object_5UwnC5BB.glb'), center: [6.485859364779873, 1.451477327044025, -6.532535446540882], normal: [-0.8850276848810058, -0.44801453664478347, -0.12652656617930816], color: "yellow" },
  { id: "object_xzlE8Fvo", glb: require('@assets/cb_object_xzlE8Fvo.glb'), center: [6.164913644444444, 2.3264866222222222, -7.3565357111111105], normal: [-0.8850276848810555, -0.44801453664461577, -0.1265265661795549], color: "yellow" },
  { id: "object_DJpb1yHO", glb: require('@assets/cb_object_DJpb1yHO.glb'), center: [5.6555031596244145, 2.9781826854460083, -6.230113483568076], normal: [-0.8850276848810442, -0.44801453664469276, -0.12652656617936145], color: "yellow" },
  { id: "object_kYlLs35V", glb: require('@assets/cb_object_kYlLs35V.glb'), center: [6.857211855421684, 0.8443536184738955, -6.95942916064257], normal: [-0.8850276848811005, -0.44801453664468693, -0.12652656617898872], color: "yellow" },
  { id: "object_jojKnw9j", glb: require('@assets/cb_object_jojKnw9j.glb'), center: [6.740465272727272, 0.8897177878787879, -6.294986545454546], normal: [-0.8850276848811922, -0.4480145366444213, -0.12652656617928762], color: "yellow" },
  { id: "object_PerMGc2e", glb: require('@assets/cb_object_PerMGc2e.glb'), center: [5.430649272727273, 3.457046565656565, -5.567481983164984], normal: [-0.9792210623378841, -0.026335450238934757, -0.2010784800384625], color: "yellow" },
  { id: "object_qER12zF3", glb: require('@assets/cb_object_qER12zF3.glb'), center: [5.352532352941176, 3.6624990392156853, -5.180852862745098], normal: [-0.9792210623378789, -0.02633545023892812, -0.20107848003848852], color: "yellow" },
  { id: "object_vtN5Xdur", glb: require('@assets/cb_object_vtN5Xdur.glb'), center: [5.320335666666666, 3.906830672727274, -5.089186381818183], normal: [-0.9792210623378742, -0.026335450238907238, -0.20107848003851445], color: "yellow" },
  { id: "object_BNkCYwQH", glb: require('@assets/cb_object_BNkCYwQH.glb'), center: [6.548114210256411, 1.095399128205128, -5.722459225641023], normal: [-0.8850276848810879, -0.4480145366445885, -0.12652656617942581], color: "yellow" },
  { id: "object_DoyROXgg", glb: require('@assets/cb_object_DoyROXgg.glb'), center: [6.410282640740741, 1.7410201259259268, -7.09535655185185], normal: [-0.8850276848810332, -0.44801453664469415, -0.12652656617943303], color: "yellow" },
  { id: "object_4lmfBePo", glb: require('@assets/cb_object_4lmfBePo.glb'), center: [6.195187848484849, 1.83836796969697, -5.839932272727273], normal: [-0.8850276848811097, -0.4480145366446357, -0.12652656617910546], color: "yellow" },
  { id: "object_z1Q4VH1F", glb: require('@assets/cb_object_z1Q4VH1F.glb'), center: [-24.124961159420288, 0.32033829710144923, -7.704141442028987], normal: [0.9499606206759696, -0.0656311981180723, -0.30539706121459764], color: "yellow" },
  { id: "object_uIe95dMa", glb: require('@assets/cb_object_uIe95dMa.glb'), center: [-24.062895942028973, 1.7780018405797102, -7.837937951690821], normal: [0.9499606206759891, -0.0656311981180429, -0.30539706121454374], color: "yellow" },
  { id: "object_HFchykJI", glb: require('@assets/cb_object_HFchykJI.glb'), center: [-23.948093921568642, 3.6361917352941173, -7.874869377450981], normal: [0.9508938135779245, -0.061416482718361615, -0.30336277119932936], color: "yellow" },
  { id: "object_2diXqfhF", glb: require('@assets/cb_object_2diXqfhF.glb'), center: [-24.266550212765956, 1.371580205673759, -8.36726795035461], normal: [0.9499606206758555, -0.06563119811806722, -0.30539706121495397], color: "yellow" },
  { id: "object_DIsfghOj", glb: require('@assets/cb_object_DIsfghOj.glb'), center: [-23.988552550724624, 2.7524184434782613, -7.849178969565215], normal: [0.9477211992736623, -0.06808130443693042, -0.3117522484817986], color: "yellow" },
  { id: "object_BGZxjyVb", glb: require('@assets/cb_object_BGZxjyVb.glb'), center: [-24.063600064102562, 0.9249259423076924, -7.64382587179487], normal: [0.949960620676006, -0.06563119811799137, -0.30539706121450233], color: "yellow" },
  { id: "object_EEAWrNDy", glb: require('@assets/cb_object_EEAWrNDy.glb'), center: [-23.932493636363635, 1.9082113333333333, -7.4427704242424255], normal: [0.9477211992737155, -0.06808130443706119, -0.31175224848160826], color: "yellow" },
  { id: "object_jr2fUVrk", glb: require('@assets/cb_object_jr2fUVrk.glb'), center: [-23.795587283950628, 3.0150067839506165, -7.260761543209877], normal: [0.9508938135779602, -0.06141648271833193, -0.3033627711992234], color: "yellow" },
  { id: "object_qydF8DiM", glb: require('@assets/cb_object_qydF8DiM.glb'), center: [-24.249691415929213, 0.9823896194690265, -8.252709631268436], normal: [0.9499606206760063, -0.06563119811805208, -0.30539706121448823], color: "yellow" },
]

export const routes: RouteDef[] = [
  { id: "route_IYBOQcvG", name: null, circuit: "Modrá", holdIds: ["object_1Py2Y4mX","object_hCyMPViQ","object_z85pxhmU","object_lSU7wmXF","object_p81FlgDF","object_LW0AW1RR","object_hX2e1VDS","object_VotzXDtf"] },
  { id: "route_uomeFalL", name: null, circuit: "Modrá", holdIds: ["object_xTzQJ2oq","object_4LxTJ0jb","object_oqUJUvt8","object_8WW1YIFB","object_VFkmaHi2","object_Y3XKY2uD","object_2ISTEbTK","object_rdC3QgCz","object_MOabpOTx","object_KBjNAtUb","object_UEgo0HaE","object_WeFCZlqA"] },
  { id: "route_ji2XQNFy", name: null, circuit: "Žlutá", holdIds: ["object_OQNcth2a","object_MCA3W8jg","object_mBhMCHI4","object_5UwnC5BB","object_xzlE8Fvo","object_DJpb1yHO","object_kYlLs35V","object_jojKnw9j","object_PerMGc2e","object_qER12zF3","object_vtN5Xdur","object_BNkCYwQH","object_DoyROXgg","object_4lmfBePo"] },
  { id: "route_T1kbJgkS", name: null, circuit: "Žlutá", holdIds: ["object_z1Q4VH1F","object_uIe95dMa","object_HFchykJI","object_2diXqfhF","object_DIsfghOj","object_BGZxjyVb","object_EEAWrNDy","object_jr2fUVrk","object_qydF8DiM"] },
]
